In [2]:
!mv ~/jupyter/*gz ./

mv: cannot stat '/home/ckasman/jupyter/*gz': No such file or directory

In [3]:
!ls

190529_CAGS_Comparison.ipynb
40_samples_sum_0.2_2019-01-21.cags.json.gz
40_samples_sum_0.3_2019-01-21.cags.json.gz
50_samples_sum_0.3_2019-01-09.cags.json.gz

In [4]:
import gzip, json   # JSON is a very common way to store data objects
import pandas as pd # Very useful module for interacting with tables
import os

def read_cags_from_json(fp):
    # Make sure that the file exists
    assert os.path.exists(fp), "File doesn't exist %s" % (fp)
    
    # Read in the data object
    dat = json.load(gzip.open(fp, "rt"))
    
    return pd.DataFrame(
        [
            {
                "cag_id": cag_id,
                "gene_id": gene_id
            }
            for cag_id, gene_id_list in dat.items() # Iterate over keys and values
            for gene_id in gene_id_list
        ]
    )

read_cags_from_json("50_samples_sum_0.3_2019-01-09.cags.json.gz").head()

  cag_id          gene_id
0     54  UniRef90_G5ETK7
1     54  UniRef90_D2NPW0
2     54  UniRef90_G5ERM8
3     54  UniRef90_D2NQ71
4     54  UniRef90_D2NRS6

In [8]:
read_cags_from_json("50_samples_sum_0.3_2019-01-09.cags.json.gz").head().set_index("gene_id")["cag_id"]

gene_id
UniRef90_G5ETK7    54
UniRef90_D2NPW0    54
UniRef90_G5ERM8    54
UniRef90_D2NQ71    54
UniRef90_D2NRS6    54
Name: cag_id, dtype: object

In [10]:
df = pd.DataFrame({
        "A": read_cags_from_json("40_samples_sum_0.2_2019-01-21.cags.json.gz").set_index("gene_id")["cag_id"],
        "B": read_cags_from_json("40_samples_sum_0.3_2019-01-21.cags.json.gz").set_index("gene_id")["cag_id"],
    }).sort_values(by="A")
df.head(40)

                 A       B
UniRef90_E0DG87  0       2
UniRef90_E0DCK9  0       2
UniRef90_E0DCK8  0       2
UniRef90_E0DCK7  0       2
UniRef90_E0DCK6  0       2
UniRef90_E0DCK4  0       2
UniRef90_E0DCK3  0       2
UniRef90_E0DCL0  0       2
UniRef90_E0DCK2  0       2
UniRef90_E0DCK0  0       2
UniRef90_E0DCJ9  0       2
UniRef90_E0DCJ8  0       2
UniRef90_E0DH56  0       2
UniRef90_E0DCJ3  0       2
UniRef90_E0DCJ2  0       2
UniRef90_E0DCK1  0       2
UniRef90_E0DCI9  0       2
UniRef90_E0DCL2  0       2
UniRef90_E0DCL5  0       2
UniRef90_E0DCP0  0       2
UniRef90_E0DCN9  0       2
UniRef90_E0DCN8  0       2
UniRef90_E0DCN7  0       2
UniRef90_E0DCN6  0       2
UniRef90_E0DCN3  0  418646
UniRef90_E0DCL3  0       2
UniRef90_E0DCN0  0       2
UniRef90_E0DCM8  0       2
UniRef90_E0DCM7  0       2
UniRef90_E0DCM6  0       2
UniRef90_E0DCM3  0       2
UniRef90_E0DCL9  0       2
UniRef90_E0DCL6  0       2
UniRef90_E0DCM9  0       2
UniRef90_E0DCI7  0       2
UniRef90_E0DCI6  0       2
UniRef90_E0DCI5  0       2
UniRef90_E0DCF4  0       2
UniRef90_E0DCF3  0       2
UniRef90_E0DCF2  0       2

In [6]:
# below list contains prime and non-prime in range 1 to 50 
noprimes = [j for i in range(2, 8) for j in range(i*2, 50, i)] 
primes = [x for x in range(2, 50) if x not in noprimes] 
print(noprimes)
print(primes)

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 10, 15, 20, 25, 30, 35, 40, 45, 12, 18, 24, 30, 36, 42, 48, 14, 21, 28, 35, 42, 49]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]